const data = [
  {
    id: 0,
    title: "PrizePicks",
    deposit: 0,
    withdrawals: 0,
    net: 0,
    currentBalance: 0,
    history: [],
  },
  {
    id: 1,
    title: "HotStreak",
    deposit: 0,
    withdrawals: 0,
    net: 0,
    currentBalance: 0,
    history: [],
  },
  {
    id: 2,
    title: "Underdog",
    deposit: 0,
    withdrawals: 0,
    net: 0,
    currentBalance: 0,
    history: [],
  },
  {
    id: 3,
    title: "DraftKings Sportsbook",
    deposit: 0,
    withdrawals: 0,
    net: 0,
    currentBalance: 0,
    history: [],
  },
  {
    id: 4,
    title: "Fanduel Sportsbook",
    deposit: 0,
    withdrawals: 0,
    net: 0,
    currentBalance: 0,
    history: [],
  },
  {
    id: 5,
    title: "Monkey Knife Fight",
    deposit: 0,
    withdrawals: 0,
    net: 0,
    currentBalance: 0,
    history: [],
  },
  {
    id: 6,
    title: "Betcha",
    deposit: 0,
    withdrawals: 0,
    net: 0,
    currentBalance: 0,
    history: [],
  },
];

export default data;
